"""empty message

Revision ID: 3292e140c8b4
Revises: a59c22909dac
Create Date: 2021-04-23 13:33:14.732119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3292e140c8b4'
down_revision = 'a59c22909dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('JuejinArticlesTable', sa.Column('draft_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('JuejinArticlesTable', 'draft_id')
    # ### end Alembic commands ###
