"""empty message

Revision ID: a59c22909dac
Revises: 235512b65610
Create Date: 2021-04-23 12:48:46.684683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59c22909dac'
down_revision = '235512b65610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JuejinArticlesTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('create_date', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('JuejinReadCount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['JuejinArticlesTable.article_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('CsdnReadCount', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CsdnReadCount', 'like_count')
    op.drop_table('JuejinReadCount')
    op.drop_table('JuejinArticlesTable')
    # ### end Alembic commands ###
